### ISSUE TITLE
Timeout getting the workflow id

### ISSUE THREAD

**Issue by prabhu-mns** [Codex-/return-dispatch#131]
Hi,

I'm trying to dispatch a workflow from one repo and wait for getting the status that workflow. When I tried to use return-dispatch, I'm getting the below error even though the PAT has right access, let me know if you need any more details. 

![image](https://user-images.githubusercontent.com/19665606/193864605-bb0863ce-7de2-4f60-bc64-bf961a2e663e.png)

**Comment by Codex-** [comment]
Has the target repository been configured to output the run ID correctly from the input? https://github.com/Codex-/return-dispatch#receiving-repository-action

**Comment by prabhu-mns** [comment]
yeah I have just configured now to output the run ID and it is working fine. Thank you for highlighting this, as I didn't know it was expecting to output run ID in the other workflow.
