### ISSUE TITLE
can not pass the custom parameters/ inputs with dispatch

### ISSUE THREAD

**Issue by ashwani280496** [Codex-/return-dispatch#171]

**Comment by Codex-** [comment]
Can you please provide more information? Customer parameters?

Can you post an example of what you want to do, and why it does not work?

**Comment by ashwani280496** [comment]
I wanted to pass the custom parameters/inputs from workflow to another workflow while dispatching.

**Comment by ashwani280496** [comment]
@Codex- any update on this?

**Comment by Codex-** [comment]
No updates as I don't have enough information yet.

Can you post an example of what you want to do? Show me with how you have your workflow yaml setup and we can go from there.

**Comment by Codex-** [comment]
I'll re-open this when more information is added

**Comment by Codex-** [comment]
Can you please post the recipient workflow?

**Comment by ashwani280496** [comment]
name: Upload Debug iOS Framework

on:
  workflow_dispatch:
    inputs:
      distinct_id:
jobs:
  build:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
      actions: write
      pull-requests: write

    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

**Comment by Codex-** [comment]
When dispatching additional inputs to the target workflow, you need to define the inputs on the recipient workflow too: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs

Extraneous inputs (those that are not defined in your recipient workflow inputs definition) will be discarded, afaik

Try adding the additional inputs you need and let me know how you go :)

**Comment by ashwani280496** [comment]
I will check and update here @Codex-

**Comment by ashwani280496** [comment]
Thanks @Codex- it worked.
