### ISSUE TITLE
dispatchWorkflow: An unexpected error has occurred: Unexpected inputs provided: ["distinct_id"]

### ISSUE THREAD

**Issue by nimroda** [Codex-/return-dispatch#188]
![image](https://github.com/Codex-/return-dispatch/assets/4217086/b4bfe183-8c82-4495-8874-906ce667aa79)

i'm not passing "distinct_id"… seems like a bug in the action.

**Comment by Codex-** [comment]
I use this action extensively, it definitely works :)

Can you please post your action usage / syntax?

**Comment by nimroda** [comment]
sure thing….

`      - name: Dispatch lifter-ui-tests workflow and get the run ID
        uses: codex-/return-dispatch@v1.11.0
        id: return_dispatch
        with:
          token: ${{ secrets.ALON_ASHKENAZI_GH_PT }}
          repo: devops-tools
          ref: main
          owner: rightbound
          workflow: lifter_ui_tests.yml
          workflow_inputs: '{"repost_to_slack": "true", "env": "staging", "triggered_from": "mono-client"}'

      - name: Await lifter-ui-tests Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.10.0
        with:
          token: ${{ github.token }}
          repo: return-dispatch
          owner: codex-
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 900 # Optional
          poll_interval_ms: 5000 # Optional`

**Comment by nimroda** [comment]
above workflow configuration throws: dispatchWorkflow: An unexpected error has occurred: Unexpected inputs provided: ["distinct_id"]

**Comment by Codex-** [comment]
This usually means the target workflow has not had the required input added:
```yaml
on:
  workflow_dispatch:
    inputs:
      distinct_id:
```
