### ISSUE TITLE
Make distinct_id configurable

### ISSUE THREAD

**Issue by fbiesse** [Codex-/return-dispatch#226]
I love this action and it's great to have 2 actions to separate 2 use cases.
I just want to make a suggestion. 
The name distinct_id can have a meaning in a context but not in another one. I wanted to know if it could be possible to make the name of the input send to the other workflow configurable with distinct_id as default value. In that way we could name it for example workflow-correlation-id for example and in our repo we would be able to create an action that uses this one to make abstraction of what's inside without to have the kind of corruption of fixed distinct_id input in all the other workflows.
I can make a PR for this if you want. 
Thank you

**Comment by Codex-** [comment]
@sayaliM0412 since you reacted, you might be interested to know this has now been implemented
