### ISSUE TITLE
Getting "Timed out while attempting to fetch data" & Runs fetched coming as empty Array[]

### ISSUE THREAD

**Issue by SangeetJoy** [Codex-/return-dispatch#245]
Hey @Codex- 

**Usecase:** 
I am trying to make a workflow dispatch call from our public repo to our private repo using codex-/return-dispatch action.

**issue:**

The call actually successfully triggers the workflow in the private repo but there are two issues.

**Issue1:** It is not waiting until 600 seconds which i passed in the `workflow_timeout_seconds: 600`

**Issue2:** It always fails after 1 minute stating - "Timed out while attempting to fetch data"

I have run the workflow in debug mode and I can see it is printing - `Runs Fetched: []` which means it is not able to fetch the run IDs. however when I use octokit to locally fetch the run IDs it actually works.

This is my calling workflow code - [this](https://github.com/XeroAPI/Xero-OpenAPI/blob/da826df45dbb426a10be099dbd917ca9e84b5826/.github/workflows/pr.yml#L57)

My receiving workflow has distinct_id as input params and also the echo step as the first step in the job.

*note - My receiving workflow is again calling 5 child workflows using workflow call.

**Please help.**

**Comment by SangeetJoy** [comment]
![IMG_0592](https://github.com/user-attachments/assets/cd499b29-13cd-44b2-b141-e0c3fe89cf40)
![IMG_0591](https://github.com/user-attachments/assets/9ab2fceb-caf7-4645-b26c-bc6186e87dba)

**Comment by SangeetJoy** [comment]
![IMG_0593](https://github.com/user-attachments/assets/c862dbd7-8e2a-4c32-8c7a-f47aa315fd42)
![IMG_0594](https://github.com/user-attachments/assets/985a01f6-12eb-406f-aaaf-d636d98815f3)

**Comment by Codex-** [comment]
Xero 👀 know a few people there

I'm having a look at the moment, will keep you posted :)

**Comment by Codex-** [comment]
Found the issue, thanks for raising this, a shame on the timing because I'm doing a fairly large breakdown for v2 that resolves this already but will backport this fix to v1

**Comment by Codex-** [comment]
@SangeetJoy fix merged, v1 tag moved to latest

Please try this and let me know if you still encounter this issue

Happy to help if you're still running into problems :)

**Comment by SangeetJoy** [comment]
Hey @Codex- Thank you for resolving the timeout code however it is still not able to fetch the run IDs as it is coming as empty Array.

I am reopening this issue, could you please check the screenshots once and help me understand why the run IDs are coming as empty array,

I have tested in local and it can fetch the run IDs.
